bookify/urls.py
from django.contrib import admin
from django.urls import path, include
# from bookreview.views import homepage  # Pastikan Anda mengimpor 'homepage' dengan benar

urlpatterns = [
    # path('', homepage, name='homepage'),  # Tambahkan path untuk halaman beranda
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('booklibrary/', include('booklibrary.urls')),
    path('bookreview/', include('bookreview.urls')), #Path bookreview diubah dari 'book/' menjadi 'bookreview/'
    path('bookcommunity/', include('bookcommunity.urls')),
    path('bookdonation/', include('bookdonation.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('api/books/', include('books.urls'))

]

bookreview/urls.py
from django.urls import path
from . import views

app_name = 'bookreview'

urlpatterns = [
    path('', views.show_library, name='show_library'),
    path('book/<int:book_id>/review/', views.book_review, name='book_review'),
    path('book/<int:book_id>/add_review/', views.ajax_add_review, name='add_review'),
    path('book/update_review/<int:review_id>', views.ajax_update_review, name='update_review'),
    path('book/delete_review/<int:review_id>', views.ajax_delete_review, name='delete_review'),
    path('favorites/', views.favorite_books, name='favorite_books'),
    path('load-books/', views.load_books_ajax, name='load_books'),
    path('load-favorites/', views.load_favorites_books_ajax, name='load_favorites'),
    path('add-favorite/<int:book_id>/', views.add_favorite_ajax, name='add_favorite'),
    path('remove-favorite/<int:book_id>/', views.remove_favorite_ajax, name='remove_favorite'),
]

books/urls.py
from django.urls import path, include
from books.views import *
app_name = 'books'

urlpatterns = [
    path("", get_books, name="get_books"),
]

homepage/urls.py
from django.urls import path, include
from homepage.views import *

app_name = 'homepage'

urlpatterns = [
    path('', show_homepage, name='show_homepage'),
    # path('book_review/', show_book_review, name='show_book_review'),
    path('json/', show_json, name='show_json'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),

]

bookreview/models.py
from django.db import models
from books.models import Books
from django.contrib.auth.models import User
from django.conf import settings

#-------------------------------------IMPORTANT!---------------------------------------------------
# ALWAYS USE 'settings.AUTH_USER_MODEL' INSTEAD OF THE USUAL 'User' WHEN CONNECTING MODELS TO USER!
# i.e. user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
#                    OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
#                    ManyToManyField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

# NOT THIS -> models.ForeignKey(User,on_delete=models.CASCADE)

# BECAUSE WE ARE USING CUSTOM USER
#--------------------------------------------------------------------------------------------------
class Review(models.Model):
    book = models.ForeignKey(to=Books, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    comment = models.TextField()

class Favorite(models.Model):
    book = models.ForeignKey(to=Books, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

books/models.py
from django.db import models

# Create your models here.
class Books(models.Model):
    title = models.TextField(null=True, blank=True)
    author = models.TextField(null=True, blank=True)
    genre = models.TextField(null=True, blank=True)
    pages = models.IntegerField(null=True, blank=True)
    published_year = models.IntegerField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    thumbnail = models.TextField(null=True, blank=True)
    ratings_avg = models.FloatField(null=True, blank=True)
    ratings_count = models.IntegerField(null=True, blank=True)
    isbn10 = models.TextField(null=True, blank=True)
    isbn13 = models.TextField(null=True, blank=True)
    

bookreview/forms.py
from django import forms
from .models import Review, Favorite
from .forms import FavoriteForm
from .forms import ReviewForm

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'rating': forms.NumberInput(attrs={'min': 1, 'max': 5}),
            'comment': forms.Textarea(attrs={'rows': 4}),
        }

class FavoriteForm(forms.ModelForm):
    class Meta:
        model = Favorite
        fields = ['book']

bookreview/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.core import serializers
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.db.models import F, Func
from books.models import Books
from django.db.models import Q

# Create your views here.
def book_review(request, book_id):
    book = get_object_or_404(Books, isbn13=book_id)
    reviews = Review.objects.filter(book=book)
    return render(request, 'bookreview.html', {'book': book, 'reviews': reviews})

@login_required
def favorite_books(request):
    user = request.user
    favorites = Favorite.objects.filter(user=user)
    return render(request, 'bookreview/favorite_books.html', {'favorites': favorites})

def show_library(request):
    return render(request, 'books.html')

@csrf_exempt
def load_books_ajax(request):
    if request.method == 'POST':
        search_query = request.POST.get('search_query')  # Ambil kata kunci pencarian dari permintaan POST

        # Ambil buku dari basis data
        if search_query:
            books = Books.objects.filter(Q(title__icontains=search_query) | Q(isbn10__icontains=search_query) | Q(isbn13__icontains=search_query))
        else:
            books = Books.objects.all()

        # Serialisasi data buku ke dalam format JSON
        serialized_books = serializers.serialize('json', books)

        # Kirim data buku sebagai respons JSON
        return JsonResponse({'status': 'success', 'books': serialized_books})

    # Jika metode permintaan tidak valid
    return JsonResponse({'status': 'error', 'message': 'Invalid request method.'})

@login_required
@csrf_exempt
def load_favorites_books_ajax(request) :
    # Mendapatkan daftar buku favorit dari pengguna yang sedang login
    favorites = Favorite.objects.filter(user=request.user)
    
    # Mengambil nilai book dari objek Favorite
    favorite_books = [favorite.book for favorite in favorites]
        
    # Serialisasi data buku ke dalam format JSON
    serialized_favorites = serializers.serialize('json', favorite_books)

    # Kirim data buku favorit sebagai respons JSON
    return JsonResponse({'status': 'success', 'favorites': serialized_favorites})

@login_required
@csrf_exempt
def add_favorite_ajax(request, book_id):
    try:
        book = Books.objects.get(pk=book_id)
        # Cek apakah buku sudah ada dalam favorit pengguna
        existing_favorite = Favorite.objects.filter(user=request.user, book=book).exists()
        if not existing_favorite:
            # Jika buku belum ada dalam favorit, tambahkan ke favorit pengguna
            favorite = Favorite(user=request.user, book=book)
            favorite.save()
            return JsonResponse({'status': 'success', 'message': 'Buku berhasil ditambahkan ke favorit.'})
        else:
            return JsonResponse({'status': 'error', 'message': 'Buku sudah ada dalam favorit.'})
    except Books.DoesNotExist:
        return JsonResponse({'status': 'error', 'message': 'Buku tidak ditemukan.'}, status=404)

@login_required
@csrf_exempt
def remove_favorite_ajax(request, book_id):
    try:
        book = Books.objects.get(pk=book_id)
        # Hapus buku dari favorit pengguna jika ada
        favorite = Favorite.objects.filter(user=request.user, book=book).first()
        if favorite:
            favorite.delete()
            return JsonResponse({'status': 'success', 'message': 'Buku berhasil dihapus dari favorit.'})
        else:
            return JsonResponse({'status': 'error', 'message': 'Buku tidak ada dalam favorit.'})
    except Books.DoesNotExist:
        return JsonResponse({'status': 'error', 'message': 'Buku tidak ditemukan.'}, status=404)
    
"""
Fungsi ini memperbarui ratings_count dan ratings_avg pada objek Books
berdasarkan perubahan rating dari review.
"""
def update_book_ratings(book, new_rating, old_rating=None, action='add'):
    if action == 'update' and old_rating is not None:
        # Menghitung ulang ratings_avg jika nilai rating berubah saat update
        book.ratings_avg = (F('ratings_avg') * F('ratings_count') - old_rating + new_rating) / F('ratings_count')
    elif action == 'delete':
        # Mengurangi 1 dari ratings_count dan menghitung ulang ratings_avg saat delete
        if book.ratings_count > 0:
            book.ratings_avg = (F('ratings_avg') * F('ratings_count') - new_rating) / (F('ratings_count') - 1)
        else:
            book.ratings_avg = 0
        book.ratings_count = F('ratings_count') - 1
    else:
        # Menambah 1 ke ratings_count dan menghitung ulang ratings_avg saat add
        book.ratings_avg = (F('ratings_avg') * F('ratings_count') + new_rating) / (F('ratings_count') + 1)
        book.ratings_count = F('ratings_count') + 1
    
    # Memanggil fungsi round() sebelum nilai ratings_avg disimpan
    book.ratings_avg = Func(F('ratings_avg'), function='ROUND', template='%(function)s(%(expressions)s, 2)')
    
    book.save()

@login_required
@csrf_exempt
def ajax_add_review(request, book_id):
    response_data = {}
    
    book = Books.objects.get(isbn13=book_id)
    
    if Review.objects.filter(book=book, user=request.user).exists():
        response_data = {'status': 'error', 'code': 400, 'message': 'Anda sudah mereview buku ini'}
    else:
        if request.method == 'POST':
            rating = request.POST.get('book_rating')
            comment = request.POST.get('book_review')
            user = request.user
            review = Review(book=book, user=user, rating=rating, comment=comment)
            review.save()
            
            # Memanggil fungsi update_book_ratings untuk mengupdate ratings_count dan ratings_avg
            update_book_ratings(book, rating, action='add')
                
            response_data = {'status': 'success', 'code': 200, 'message': "Review berhasil ditambahkan."}
    
    return JsonResponse(response_data)

@login_required
@csrf_exempt
def ajax_update_review(request, review_id):
    response_data = {}
    
    review = get_object_or_404(Review, pk=review_id, user=request.user)
    
    if request.method == 'POST':
        rating = request.POST.get('book_rating')
        comment = request.POST.get('book_review')
        
        # Memanggil fungsi update_book_ratings untuk mengupdate ratings_count dan ratings_avg
        update_book_ratings(review.book, rating, review.rating, action='update')
        
        review.rating = rating
        review.comment = comment
        review.save()
        response_data = {'status': 'success', 'code': 200, 'message': "Review berhasil diedit."}

    return JsonResponse(response_data)

@login_required
@require_POST
@csrf_exempt
def ajax_delete_review(request, review_id):
    response_data = {}
    review = get_object_or_404(Review, pk=review_id)

    # Memanggil fungsi update_book_ratings untuk mengupdate ratings_count dan ratings_avg
    update_book_ratings(review.book, review.rating, action='delete')
    
    if review.delete() :
        response_data = {'status': 'success', 'code': 200, 'message': "Review berhasil dihapus."}
    return JsonResponse(response_data)
        

books/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers

from books.models import Books

# Create your views here.
def get_books(request):
    data = Books.objects.all()
    return HttpResponse(serializers.serialize("json", data),
    content_type = "application/json")

bookreview/templates/book.html
{% extends "layout.html" %}

{% load static %}

{% block head %}
    <!--Icon-->
    <link rel="icon" href="{% static 'icons/icons8-repository-48.png' %}" rel="icon">
{% endblock %}

{% block title %}
    {{ book.title }}
{% endblock %}

{% block body %}
    <div class="container container-fluid mt-5">
        <div class="row search-row justify-content-center">
            <div class="col-lg-8 col-md-6 col-8 pt-6 mb-3">
                <div class="card">
                    <div class="card-header">
                        {{ book.author }}, {{ book.published_date }}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                            <strong>{{ book.title }}</strong>
                        </h5>
                        <p class="card-text">
                            <strong>ISBN: </strong>{{ book.isbn10 }}<br>
                            <strong>Goodreads Reviews: </strong> {{ book.description }}<br>
                            <strong>Average Rating: </strong> {{ book.average_rating }} <br>
                        </p>
                        <a href="#review-form" class="btn btn-primary" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="review-form">Write a review</a>
                    </div>
                    <div class="collapse" id="review-form">
                        <!-- Form untuk menulis review -->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

bookreview/templates/bookreview.html
{% extends "layout.html" %} {% load static %} {% block head %}
<!--Icon-->
<link href="static/icons/icons8-repository-48.png" rel="icon" />
{% endblock %} {% block title %} {{ book.title }} {% endblock %}
<!-- Body -->
{% block body %}
<div class="container mt-5">
  <div class="col-10 col-lg-8 pt-6 mb-3 mx-auto">
    <div class="card">
      <div class="card-header">Book Details</div>
      <div class="card-body">
        <div class="row mb-4">
          <div class="col-12 col-md-4">
            <img
              src="{{ book.thumbnail }}"
              alt="book thumbnail"
              class="img-fluid w-100"
            />
          </div>
          <div class="col">
            <h5 class="card-title">{{ book.title }}</h5>
            <p class="card-text">{{ book.description }}</p>
            <p class="fw-bold">{{ book.genre }} | {{ book.published_year }}</p>
            <p class="m-0"><b>Author :</b> {{ book.author }}</p>
            <p class="m-0"><b>Pages :</b> {{ book.pages }}</p>
            <p class="m-0"><b>Rating :</b> {{ book.ratings_avg }}/5</p>
            <p class="m-0"><b>Total Reviewer :</b> {{ book.ratings_count }}</p>
            <p class="m-0"><b>ISBN-10 :</b> {{ book.isbn10 }}</p>
            <p class="m-0"><b>ISBN-13 :</b> {{ book.isbn13 }}</p>
          </div>
        </div>

        {% if user.is_authenticated %}
        <a
          href="#review-form"
          id="writeReview"
          class="btn btn-primary"
          role="button"
          data-bs-toggle="modal"
          data-bs-target="#reviewModal"
          data-edit-url="{% url 'bookreview:add_review' book_id=book.isbn13 %}"
          >Write a review</a
        >
        {% endif %}
      </div>
    </div>
  </div>
  <div class="col-10 mt-10 mx-auto">
    <hr class="border-white" />
    <h4><strong>User reviews:</strong></h4>
  </div>
  <div class="row user-reviews justify-content-center">
    {% for review in reviews %}
    <div
      class="col-10 mt-3 {% if request.user.is_authenticated and review.user == request.user %}order-1{% else %}order-2{% endif %}"
    >
      <div class="card bg-light mb-3">
        <div class="card-body">
          <h6 class="card-subtitle mb-2">{{ review.user.username }}</h6>
          <h5 class="card-title">
            <strong
              >Rating :
              <i class="fa fa-star" style="color: #ffc107"></i>
              {{review.rating}}</strong
            >
          </h5>
          <p class="card-text">{{ review.comment }}</p>
        </div>
        {% if review.user == request.user or request.user.role == 'moderator' %}
        <div class="card-footer">
          {% if review.user == request.user %}
          <button
            type="button"
            id="editReviewButton"
            class="btn btn-sm btn-warning"
            data-rating="{{ review.rating }}"
            data-comment="{{ review.comment }}"
            data-edit-url="{% url 'bookreview:update_review' review_id=review.pk %}"
          >
            Edit
          </button>
          {% endif %}
          <button
            type="button"
            class="btn btn-sm btn-danger"
            data-bs-toggle="modal"
            data-bs-target="#deleteModal{{ review.pk }}"
          >
            Delete
          </button>
        </div>
        {% endif %}
      </div>
    </div>

    {% if review.user == request.user or request.user.role == "moderator" %}
    <!-- Modal Delete -->
    <div
      class="modal fade"
      id="deleteModal{{ review.pk }}"
      tabindex="-1"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Review</h1>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            ></button>
          </div>
          <div class="modal-body">Delete your review?</div>
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary"
              data-bs-dismiss="modal"
            >
              Close
            </button>
            <form
              action="{% url 'bookreview:delete_review' review_id=review.pk %}"
              method="POST"
              id="delete"
            >
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">
                Yes, Delete Review
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
    {%endif%} {% endfor %}
  </div>
</div>

<!-- Review Modal -->
<div
  class="modal fade"
  id="reviewModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <form
        action=""
        method="POST"
        class="needs-validation"
        id="review"
        novalidate
      >
        {% csrf_token %}
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Review Book</h1>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <div class="form-group review-form">
            <input
              type="text"
              class="form-control"
              id="book-review"
              name="book_review"
              aria-describedby="emailHelp"
              placeholder="Write a short review."
            />
            <div class="review-checkbox">
              <strong>Rating : <br /></strong>
              <div class="form-check form-check-inline">
                <input
                  class="form-check-input"
                  type="radio"
                  name="book_rating"
                  id="rating1"
                  value="1"
                />
                <label class="form-check-label" for="rating1">
                  <i class="fas fa-star"></i>
                </label>
              </div>
              <div class="form-check form-check-inline">
                <input
                  class="form-check-input"
                  type="radio"
                  name="book_rating"
                  id="rating2"
                  value="2"
                />
                <label class="form-check-label" for="rating2">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                </label>
              </div>
              <div class="form-check form-check-inline">
                <input
                  class="form-check-input"
                  type="radio"
                  name="book_rating"
                  id="rating3"
                  value="3"
                />
                <label class="form-check-label" for="rating3">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                </label>
              </div>
              <div class="form-check form-check-inline">
                <input
                  class="form-check-input"
                  type="radio"
                  name="book_rating"
                  id="rating4"
                  value="4"
                />
                <label class="form-check-label" for="rating4">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                </label>
              </div>
              <div class="form-check form-check-inline">
                <input
                  class="form-check-input"
                  type="radio"
                  name="book_rating"
                  id="rating5"
                  value="5"
                />
                <label class="form-check-label" for="rating5">
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                </label>
              </div>
            </div>
            <hr />
          </div>
        </div>
        <div class="modal-footer">
          <div class="login-submit-container">
            <button type="submit" class="btn btn-success login-submit-button">
              Leave a review
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %} {% block js_page %}
<script>
  // AJAX untuk mengirim formulir review
  $(document).ready(function () {
    $("#editReviewButton").click(function (e) {
      const rating = $(this).data("rating");
      const comment = $(this).data("comment");
      const editUrl = $(this).data("edit-url");
      console.log(rating, comment, editUrl);
      $(`#rating${rating}`).prop("checked", true);
      $("#book-review").val(comment);
      $("form#review").prop("action", editUrl);

      $("#reviewModal").modal("show");
    });

    $("#writeReview").click(function () {
      $("form#review").prop("action", $(this).data("edit-url"));
      $("#book-review").val("");
      $('input[name="book_rating"]:checked').prop("checked", false);
    });

    $("form#review").submit(function (event) {
      event.preventDefault();

      $.ajax({
        type: "POST",
        url: $(this).attr("action"),
        data: $(this).serialize(),
        success: function (response) {
          // Handle success response if needed
          if (response.status === "success") {
            // Review berhasil ditambahkan, lakukan tindakan sesuai kebutuhan
            alert(response.message);
            // Misalnya, muat ulasan kembali setelah review ditambahkan
            // Implementasikan logika tampilan ulasan di sini
          } else {
            // Review gagal ditambahkan, tampilkan pesan error
            alert(response.message);
          }
        },
        error: function (error) {
          // Handle error response if needed
          alert("Terjadi kesalahan saat mengirim review.");
        },
      });
    });

    // AJAX untuk mengirim permintaan penghapusan review
    $("form#delete").submit(function () {
      event.preventDefault();

      // Mengirim permintaan AJAX ke endpoint penghapusan review dengan reviewId sebagai parameter
      $.ajax({
        type: "POST",
        url: $(this).attr("action"),
        data: $(this).serialize(),
        success: function (response) {
          // Handle success response if needed
          // Misalnya, menampilkan pesan sukses atau memperbarui tampilan ulasan pengguna
          alert(response.message);
        },
        error: function (error) {
          alert("Terjadi kesalahan saat menghapus review.");
        },
      });
    });
  });

  $(document).ajaxStop(function () {
    window.location.reload();
  });
</script>
{% endblock %}

bookreview/templates/layout.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
  crossorigin="anonymous"
/>
<!--<script
  src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  crossorigin="anonymous"
></script>-->
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
  crossorigin="anonymous"
></script>
<script
  src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
  crossorigin="anonymous"
></script>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
  integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
<link rel="stylesheet" href="{% static 'styles/style.css' %}" />

{% block head %}{% endblock %}

<title>| {% block title %}{% endblock %}</title>
<style media="screen">
  .navbar-brand {
    font-size: 24px !important;
  }
  .nav-item {
    font-size: 20px !important;
  }
</style>
{% endblock %} {% block content %}
<!--TODO: Add NavBar with: App Name, LogIn, LogOut, Register, etc-->
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div
        class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start"
      >
        <div class="flex flex-shrink-0 items-center">
          <h1 class="font-bold text-blue-500 text-2xl mt-0.5 mb-1 ml-0.5">
            B O O K I F Y
          </h1>
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <a
              href="{% url 'homepage:show_homepage' %}"
              class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
              >Home</a
            >
            <a
              href="{% url 'bookreview:show_library' %}"
              class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
              >Book List</a
            >
          </div>
        </div>
      </div>
      <div
        class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0"
      >
        <button
          type="button"
          class="rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800"
        >
          <span class="sr-only">View notifications</span>
        </button>

        <div class="relative ml-3">
          {% if not user.is_authenticated %}
          <div>
            <button
              class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
              onclick="location.href='/login/'"
            >
              Login
            </button>
          </div>
          {% else %}

          <div class="flex space-x-4">
            <p
              class="text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
            >
              {{user.get_username}}
            </p>
            <button
              class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
              onclick="location.href='/logout/'"
            >
              Logout
            </button>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</nav>

{% block body %}{% endblock %}

<footer class="p-4 bg-white shadow md:px-6 md:py-8 dark:bg-gray-900">
  <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
  <span class="block text-sm text-gray-500 sm:text-center dark:text-gray-400">
    © 2023 Bookify™. All Rights (not) Reserved.
  </span>
</footer>

{% block js_page %}{% endblock %} {% endblock %}